version: '3.8'

services:
  client:
    build:
      context: ./client  # client 디렉토리
      dockerfile: Dockerfile  # client용 Dockerfile
    ports:
      - "3000:3000"
  
  server:
    build:
      context: ./server  # server 디렉토리
      dockerfile: Dockerfile  # server용 Dockerfile
    ports:
      - "8080:8080"